language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: DBgsI8dDYL6OIN79o7o5xxyVhJXPJVxLyoHY7uX2XMjRXamr02+mSt4e9q/4YXM1MKC8XF6Y9whPia5tN0vw4zGZV7X6uvBn58SSpMeRoKTJ/7CvYT4dSN7PJtSTh1XxaECSU5l2xlKExZB+joRcNLEJCnGaKxz64CWNTSgKEkYEyMVjE0qCmihPgP8YDKEE/TmHcdg+fwx66Cpzdj+neF+KFimj0WtXjQrTLSimI6Pf6D8uVq3n/kCCwclh0kO3wXhgHLR1s3Rh+jE4CaZNvNEUXn6kiXDxs2EqzcTbAuRmZOBo+4Z3ScNrWrY5thYtq8lM3unbqhaL77vVA455bIXmH0aOMI85ADLsW8ThQifRSgX4LpbY9xAlnjFtaC9GAnNEGoQtdm3br5ORFs5RSWeE1o5Z+yh7UPYzSAGQfL+iRD92Yw6YejTg+EMOoxyRoTvIgfbLTbWh0embygX2sMUQiG8gHnXhJtndCw1ua4B65gGCwQd4oCf3Xo0K+GBQ2t90cd1gz5621r4rcPvsmhKAYHJ2kcCwQ6F2urmUnAPwIil6saxm/9o/9ZER0N2sHGiJUKZUf8UpZTO+MH6+Oi0kqXdBA90AglMLD7dSvIf+qzTelf8OJqkFc2EM6/3EA0O6oYUlZ745c1fwxNr3OkhjT5ykg7b8hrq3K85iIRU=
  file:
    - 'is-decimal.js'
    - 'is-decimal.min.js'
  on:
    tags: true
